### ISSUE TITLE
More Clarification for Where to Put a Global CSS File

### ISSUE THREAD

**Issue by Khongchai** [mui/react-technical-challenge#23]
I was doing the challenge a few hours ago when this error came up (only while running the test)

<img width="1088" alt="error" src="https://user-images.githubusercontent.com/56601823/221405993-d51b6d67-c007-4879-b8aa-b32cc56cf836.png">

After spending a lot of time troubleshooting, I found out that the root cause was a CSS file that I had put in the component folder next to the tsx file.

Now, I am not sure whether this is a known issue or a quirk of the testing library -- or that I was wrong to think that putting a CSS file like that is still allowed in the current Next version.  I still think that it would be helpful to address this somewhere in the README.md file. The error it threw made it even more confusing.

ps. the error is different from this module issue https://github.com/mui/react-technical-challenge/issues/11

**Comment by oliviertassinari** [comment]
I think that we should update the challenge to have a blank CSS file. We can add a comment that says that folks who wants to write CSS rather than CSS-in-JS can use it.

**Comment by oliviertassinari** [comment]
Would this #24 help?

**Comment by Khongchai** [comment]
I think this is pretty helpful. If I had to start over, I'd use the .module.css rather than create my own. 

Thanks!

I'll close this issue.

**Comment by oliviertassinari** [comment]
OK thanks, merged.

cc @mnajdova for context, as it will be interesting to retain this with an update of the challenge to more in sync with the repository, Node 18, etc.
